cumbia-magic plugin: CuMagic Class Reference
CuMagic Class Reference
#include <cumagic.h>
Public Types
enum TargetDataType { Scalar , Vector , List }
Signals
void newData (const CuData &da)
Public Member Functions
CuMagic (QObject *target, CumbiaPool *cu_pool, const CuControlsFactoryPool &fpoo, const QString &source=QString(), const QString &property=QString())
CuMagic::CuMagic magic object that can be attached to any Qt object to display read values.
~CuMagic ()
void setErrorValue (const CuVariant &v)
setErrorValue in case of read error, display this value
QString & operator[] (std::size_t idx)
const QString & operator[] (std::size_t idx) const
void map (size_t idx, const QString &onam)
void map (size_t idx, QObject *obj, const QString &prop=QString())
opropinfo & find (const QString &onam)
find find the opropinfo associated to a given object name
void mapProperty (const QString &from, const QString &to)
mapProperty instruct CuMagic to use property to instead of from
QString propMappedFrom (const char *to)
propMappedFrom given the to property, returns the property from associated to to by mapProperty
QString propMappedTo (const char *from)
propMappedTo given the from property, returns the property from is mapped to
void onUpdate (const CuData &data)
void setSource (const QString &src)
set the source to read from.
void unsetSource ()
Remove the reader.
QString source () const
returns the configured source
QObject * get_target_object () const
get_object returns the QObject used in CuMagicPluginInterface::getMagic
void sendData (const CuData &da)
send data to the reader
CuContext * getContext () const
get the context used by the multireader
QString format () const
get the suggested format to use when displaying the number, if available from the configuration stage.
QString display_unit () const
get the measurement unit, if available from the configuration stage
Public Member Functions inherited from CuMagicI
virtual ~CuMagicI ()
Member Enumeration Documentation
TargetDataType
enum CuMagic::TargetDataType
Enumerator
Scalar
Vector
List
Constructor & Destructor Documentation
CuMagic()
CuMagic::CuMagic (QObject * target, CumbiaPool * cu_pool, const CuControlsFactoryPool & fpoo, const QString & src = QString(), const QString & property = QString())
Parameters
target the target object, which becomes the parent of this object (means automatic destruction)
cu_pool a pointer to a previously allocated CumbiaPool
fpoo a const reference to CuControlsFactoryPool
src the source for the readings. Can additionally be provided later with setSource
property if specified, write the provided property instead of automatically guessing the property
Implementation
CuMagic reads from source and tries to display the result according to the available properties of the target object, in this order:
value
checked
text
Error handling
If an error occurs and the property disable_on_error is not defined or defined and set to false, and the target is a widget, then the widget is disabled on error. The contents of msg stored in the data is set as tooltip, if the target is a widget
New data notification
New data is notified by the newData signal
Properties
disable_on_error: if false, a read error does not disable the target. Default: if widget, the target is disabled
References CuMagicPrivate::context, CuMagicPrivate::format, CuMagicPrivate::on_error_value, CuMagicPrivate::onetime, setSource(), and CuMagicPrivate::t_prop.
~CuMagic()
CuMagic::~CuMagic ()
References CuMagicPrivate::context.
Member Function Documentation
display_unit()
QString CuMagic::display_unit () const virtual
Returns
the measurement unit, or an empty string if the display_unit key is not found within the configuration data.
Implements CuMagicI.
References CuMagicPrivate::display_unit.
find()
opropinfo & CuMagic::find (const QString & onam) virtual
Parameters
onam object name to search
Returns
a reference to an opropinfo, if found, an empty opropinfo otherwise
Implements CuMagicI.
References CuMagicPrivate::omap.
format()
QString CuMagic::format () const virtual
Returns
a string defining the format for numbers, e.g. "%.2f", "%d" or an empty string if the format key in the configuration data is not defined.
Implements CuMagicI.
References CuMagicPrivate::format.
get_target_object()
QObject * CuMagic::get_target_object () const virtual
Returns
the Qt object (QObject, QWidget, ...) used in CuMagicPluginInterface::getMagic as the target where read values are displayed
Implements CuMagicI.
getContext()
CuContext * CuMagic::getContext () const virtual
Returns
a pointer to the CuContext in use, which is nullptr if init has not been called yet
Implements CuMagicI.
References CuMagicPrivate::context.
map() [1/2]
void CuMagic::map (size_t idx, const QString & onam) virtual
Implements CuMagicI.
References CuMagicPrivate::omap.
map() [2/2]
void CuMagic::map (size_t idx, QObject * obj, const QString & prop = QString()) virtual
Implements CuMagicI.
References CuMagicPrivate::omap.
mapProperty()
void CuMagic::mapProperty (const QString & from, const QString & to) virtual
Parameters
from a property name known to the plugin (e.g. *value, text, min, max *)
to a property name known to the object (e.g. min --> yLowerBound, max --> yUpperBound, text --> html)
This method can be used to tell CuMagic to operate on the property to instead of from. from is one of the properties known by CuMagic, such as min, max, value, text, ...
Implements CuMagicI.
References CuMagicPrivate::propmap.
newData
void CuMagic::newData (const CuData & da) signal
Referenced by onUpdate().
onUpdate()
void CuMagic::onUpdate (const CuData & data)
References newData(), opropinfo::obj, CuMagicPrivate::omap, CuMagicPrivate::on_error_value, CuMagicPrivate::onetime, opropinfo::prop, source(), CuMagicPrivate::t_prop, and unsetSource().
operator[]() [1/2]
QString& CuMagic::operator[] (std::size_t idx)
operator[]() [2/2]
const QString& CuMagic::operator[] (std::size_t idx) const
propMappedFrom()
QString CuMagic::propMappedFrom (const char * to) virtual
Parameters
to the name of the property known to the object, associated by the mapProperty method
Returns
the property name known to CuMagic that was mapped to to by mapProperty
Implements CuMagicI.
References CuMagicPrivate::propmap.
propMappedTo()
QString CuMagic::propMappedTo (const char * from) virtual
Parameters
from the property name known to the CuMagic, f.e. min, max, value, text, format, display_unit
Returns
the property name to which from has been associated by mapProperty
Implements CuMagicI.
References CuMagicPrivate::propmap.
sendData()
void CuMagic::sendData (const CuData & da) virtual
Parameters
da the data
Implements CuMagicI.
References CuMagicPrivate::context.
setErrorValue()
void CuMagic::setErrorValue (const CuVariant & v) virtual
Parameters
v the value to show in case of error
Implements CuMagicI.
References CuMagicPrivate::on_error_value.
setSource()
void CuMagic::setSource (const QString & src) virtual
Note
Calling this method replaces the existing source with the new ones
Implements CuMagicI.
References CuMagicPrivate::context, CuMagicPrivate::src, and CuMagicPrivate::v_idxs.
Referenced by CuMagic().
source()
QString CuMagic::source () const virtual
Implements CuMagicI.
References CuMagicPrivate::context.
Referenced by onUpdate().
unsetSource()
void CuMagic::unsetSource () virtual
Implements CuMagicI.
References CuMagicPrivate::context.
Referenced by onUpdate().
The documentation for this class was generated from the following files:
cumagic.h
cumagic.cpp