cumbia-magic plugin: CuMagicPluginInterface Class Reference
CuMagicPluginInterface Class Reference abstract
#include <cumagicplugininterface.h>
Public Member Functions
virtual ~CuMagicPluginInterface ()
virtual void init (CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)=0
Initialise the multi reader with mixed engine mode and the read mode.
virtual const QObject * get_qobject () const =0
To provide the necessary signals aforementioned, the implementation must derive from Qt QObject. This method returns the subclass as a QObject, so that the client can connect to the multi reader signals.
virtual CuMagicI * new_magic (QObject *target, const QString &source=QString(), const QString &property=QString()) const =0
get_magic returns a new CuMagicI object with target the given QObject and source
Static Public Member Functions
static CuMagicPluginInterface * get_instance (CumbiaPool *cu_poo, const CuControlsFactoryPool &fpoo, QObject **plugin_qob)
CuMagicPluginInterface::get_instance returns a new instance of the plugin.
static QString file_name ()
Constructor & Destructor Documentation
~CuMagicPluginInterface()
virtual CuMagicPluginInterface::~CuMagicPluginInterface () inline virtual
Member Function Documentation
file_name()
static QString CuMagicPluginInterface::file_name () inline static
Referenced by get_instance().
get_instance()
static CuMagicPluginInterface* CuMagicPluginInterface::get_instance (CumbiaPool * cu_poo, const CuControlsFactoryPool & fpoo, QObject ** plugin_qob) inline static
Parameters
cu_poo pointer to a previously allocated CumbiaPool
fpoo const reference to CuControlsFactoryPool
mode one of CuMagicPluginInterface::Mode modes
plugin_qob a pointer to a QObject, will contain this plugin as QObject (for signals and slots)
Returns
an instance of the plugin or nullptr in case of failure.
Note
Repeated calls will return the same plugin instance (by Qt plugin nature) Use either getMultiSequentialReader or getMultiConcurrentReader to get new instances of multi readers instead
References file_name(), and init().
get_qobject()
virtual const QObject* CuMagicPluginInterface::get_qobject () const pure virtual
Returns
The object implementing CuMagicI as a QObject.
Implemented in CuMagicPlugin.
init()
virtual void CuMagicPluginInterface::init (CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool) pure virtual
Parameters
cumbia a reference to the CumbiaPool engine chooser
r_fac the CuControlsFactoryPool factory chooser
Implemented in CuMagicPlugin.
Referenced by get_instance().
new_magic()
virtual CuMagicI* CuMagicPluginInterface::new_magic (QObject * target, const QString & source = QString(), const QString & property = QString()) const pure virtual
Parameters
parent the object used as target to display the read values
source the source of the readings
Returns
a new instance of an object implementing CuMagicI interface
Implemented in CuMagicPlugin.
The documentation for this class was generated from the following file:
cumagicplugininterface.h